name: Java CI with Gradle and Maven

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build all projects
        run: |
          echo "Building all projects..."
          find . -name "pom.xml" | while read -r mavenProjectDir; do
            project_dir=$(dirname "mavenProjectDir")
            echo "Building project: $project_dir"
            (cd "$project_dir" && mvn clean install)
          done